### ISSUE TITLE
Describe the spec using json schema

### ISSUE THREAD

**Issue by tmnd1991** [agile-lab-dev/Data-Product-Specification#9]
May I suggest to maintain a json schema and possibly autogenerate the example.yaml (or simply check it during CI?) that would help users a lot!

if you agree I might work on it

**Comment by SpyQuel** [comment]
I think we solved this issue with #13 (we actually used CUE since it is more expressive than JSON schema).
Could it solve this issue?

**Comment by tritemio** [comment]
If needed a JSON schema may be generate from the cue file. In principle we can also autogenerate the YAML, but we should provide an additional CUE with concrete values for each field (used as examples). However I think it's better to just validate the example.yaml against the CUE so that the YAML can also contain comments.

**Comment by tmnd1991** [comment]
Yes I guess it’s solved. A bit pro of json schema is that IDEs support it so it’s possible to have auto completion when writing the “code”.
